CREATE TABLE category (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name NVARCHAR(60) NOT NULL,
	remark NVARCHAR(60) NOT NULL
);

CREATE TABLE tag (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name NVARCHAR(60) NOT NULL,
	remark NVARCHAR(60) NOT NULL
);

CREATE TABLE book (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	isbn NVARCHAR(15) UNIQUE DEFAULT NULL,
	title NVARCHAR(60) NOT NULL,
	author NVARCHAR(60) NOT NULL,
	publisher NVARCHAR(60) NOT NULL,
	pubdate NVARCHAR(15) NOT NULL,
	category INTEGER NOT NULL,
	cover NVARCHAR(100),
	FOREIGN KEY (category) REFERENCES category(id)
);

CREATE TABLE book_tag (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	book_id INTEGER NOT NULL,
	tag_id INTEGER NOT NULL,
	FOREIGN KEY (book_id) REFERENCES book(id),
	FOREIGN KEY (tag_id) REFERENCES tag(id)
);
